trigger:
- main

pool:
  name: Default

variables:
  - group: DockerVariables  # Asegúrate de que este grupo tenga la variable dockerHubUser
  - name: dockerHubUser
    value: 'tu-usuario-dockerhub'  # Reemplaza por tu usuario de Docker Hub
  - name: imageName
    value: 'mi-aplicacion'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: build
        repository: $(dockerHubUser)/$(imageName)
        dockerfile: Dockerfile
        tags: |
          latest
          $(Build.BuildId)

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: Docker@2
      displayName: 'Push Docker image to Docker Hub'
      inputs:
        command: push
        repository: $(dockerHubUser)/$(imageName)
        tags: |
          latest
          $(Build.BuildId)
        containerRegistry: 'Docker Hub'
        dockerRegistryEndpoint: 'DockerHubConnection'

    - script: |
        echo "Haciendo pull de la última versión de la imagen..."
        docker pull $(dockerHubUser)/$(imageName):latest
      displayName: 'Pull Docker image from Docker Hub'

    - script: |
        echo "Deteniendo y eliminando contenedor existente si es necesario..."
        docker stop prueba || true
        docker rm prueba || true
      displayName: 'Stop and remove existing container'

    - script: |
        echo "Ejecutando contenedor con la nueva imagen..."
        docker run -d --name prueba -p 8080:80 $(dockerHubUser)/$(imageName):latest
      displayName: 'Run Docker container with updated image'

    - script: |
        echo "Agregando tag al commit..."
        git config user.email "armanditosigo@gmail.com"
        git config user.name "nightfurygt1"
        git tag -a "v$(Build.BuildId)" -m "Tag de despliegue para la build $(Build.BuildId)"
        git push origin --tags
      displayName: 'Tag commit in repository'
